[build]
command = "npm run sitemap && npm run scripts:build:data -- --dry-run=false && npm run test:jest && npm run build"
publish = "dist"

[build.environment]
TERM = "xterm"

[[plugins]]
# local Cypress plugin will test our site after it is built
package = "netlify-plugin-cypress"
  [plugins.inputs]
  spa = true

# redirects

[[redirects]]
  from = "/chapters"
  to = "/events"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404
